name: demo gha cache bug

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0
          buildkitd-flags: --debug
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
